version: "3.1"

networks:
  app-network:
    driver: bridge

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./mongo/db:/data/db
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: "${DB_NAME}"
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    networks:
      - app-network

  mongoclient:
    image: mongoclient/mongoclient
    ports:
      - 3001:3000
    networks:
      - app-network